version: '3'

services:
  web:
    build: .
    command: gunicorn  deals_stone.wsgi:application --bind 0.0.0.0:8001
    container_name: django-deals_stone
    expose:
      - 8001
    volumes:
      - static_volume:/usr/src/app/static
    env_file:
      - ./.env.dev
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - web

  db:
    image: postgres:12.0-alpine

    env_file:
      - ./.env.dev

    ports:
      - "192.168.1.163:5444:5432"

    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
