version: '3'

services:
  web:
    build: .
    command: gunicorn  deals_stone.wsgi:application --bind 0.0.0.0:8001
    container_name: django-deals_stone
    expose:
      - 8001
    volumes:
      - static_volume:/usr/src/app/static
    environment:
      - DJANGO_DEBUG=0
      - DGANGO_SECRET_KEY=my_secret_key_322_3_xya
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1] *
      - DJANGO_IP_PORT=8000
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=django_prod
      - SQL_USER=admin
      - SQL_PASSWORD=admin_pgs
      - SQL_HOST=db
      - SQL_PORT=5432

    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - web

  db:
    image: postgres:12.0-alpine

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_pgs
      - POSTGRES_DB=django_prod

    ports:
      - 5444:5432

    volumes:
      - ./postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  static_volume:
